export enum OrderStatus {
  OPEN = 'OPEN', 
  PREPARING = 'PREPARING',
  ON_THE_WAY = 'ON THE WAY',
  DELIVERED = 'DELIVERED',
  CANCELLED_BY_RESTAURANT = 'CANCELLED BY RESTAURANT',
  FAILED_DELIVERY = 'FAILED DELIVERY'
}